<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-11 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.2.8 on 2023-12-07 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> origin/development


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
<<<<<<< HEAD
                ('educationalLevel', models.CharField(choices=[('Primary', 'Primary School'), ('High School', 'High School'), ('Collage', 'Collage'), ('Doctoral Student', 'Doctoral'), ('Ph.D', 'Graduate')], default='High School', max_length=20)),
=======
                ('educationalLevel', models.CharField(choices=[('Primaria', 'Primary School'), ('Secundaria', 'High School'), ('Universidad', 'Collage'), ('Postgrado', 'Graduate')], default='Secundaria', max_length=20)),
>>>>>>> origin/development
                ('occupation', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
