# Generated by Django 5.0.4 on 2025-10-31 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainingApp', '0002_initial'),
        ('userApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('educationalLevel', models.CharField(choices=[('Primary School', 'Primary School'), ('High School', 'High School'), ('Associate', 'Associate'), ('University', 'University'), ('Doctoral Student', 'Doctoral Student'), ('Magister', 'Magister'), ('Doctor', 'Doctor')], default='High School', max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainingApp.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
