# Generated by Django 5.0.1 on 2024-04-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0010_rename_gruops_training_groups'),
        ('userApp', '0002_trainee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainingApp.group'),
        ),
    ]
