# Generated by Django 5.0.4 on 2024-08-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_trainee_educationallevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='educationalLevel',
            field=models.CharField(choices=[('Primary School', 'Primary School'), ('High School', 'High School'), ('Associate', 'Associate'), ('University', 'University'), ('Doctoral Student', 'Doctoral Student'), ('Magister', 'Magister'), ('Doctor', 'Doctor')], default='High School', max_length=50),
        ),
    ]
