# Generated by Django 5.0.1 on 2024-02-28 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, null=True)),
                ('deploy_image', models.ImageField(blank=True, upload_to='trainingApp/images')),
                ('deploy_sound', models.FileField(blank=True, upload_to='trainingApp/sound')),
                ('correct_answer', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeployType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_training', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Intemediate', 'Intemediate'), ('Advanced', 'Advanced')], default='Easy', max_length=20)),
                ('estimatedDuration', models.IntegerField(default=0)),
                ('state_training', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, null=True)),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploy')),
            ],
        ),
        migrations.AddField(
            model_name='deploy',
            name='deploy_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploytype'),
        ),
        migrations.CreateModel(
            name='TraineeTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='upload date')),
                ('state', models.CharField(default='in_progress', max_length=100)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.trainee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training')),
            ],
        ),
        migrations.CreateModel(
            name='DeployAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.CharField(max_length=50, null=True)),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploy')),
                ('trainee_Training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.traineetraining')),
            ],
        ),
        migrations.AddField(
            model_name='deploy',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_liked', models.CharField(choices=[('Well explained', 'Well Explained'), ('Interesting', 'Interesting'), ('Easy to understand', 'Easy To Understand')], max_length=20)),
                ('least_liked', models.CharField(choices=[('Too difficult', 'Too Difficult'), ('Not interesting', 'Not Interesting'), ('Poorly explained', 'Poorly Explained'), ('Confusing', 'Confusing'), ('Repetitive', 'Repetitive')], max_length=20)),
                ('comment_aditional', models.CharField(max_length=500)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('pub_date', models.DateTimeField(verbose_name='upload date')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.trainee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training')),
            ],
        ),
    ]
