# Generated by Django 5.0.1 on 2024-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='attempts_allowed',
            field=models.IntegerField(default=1),
        ),
    ]
