# Generated by Django 5.0.4 on 2025-10-31 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('estimed_duration_block', models.IntegerField(default=0)),
                ('state_block', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100, null=True)),
                ('correctChoice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_liked', models.CharField(choices=[('Well explained', 'Well explained'), ('Interesting', 'Interesting'), ('Easy to understand', 'Easy to understand')], max_length=20)),
                ('least_liked', models.CharField(choices=[('Too difficult', 'Too difficult'), ('Not interesting', 'Not interesting'), ('Poorly explained', 'Poorly explained'), ('Confusing', 'Confusing'), ('Repetitive', 'Repetitive')], max_length=20)),
                ('comment_aditional', models.CharField(max_length=500)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('pub_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, null=True)),
                ('deploy_image', models.ImageField(blank=True, upload_to='trainingApp/images')),
                ('deploy_sound', models.FileField(blank=True, upload_to='trainingApp/sound')),
            ],
        ),
        migrations.CreateModel(
            name='DeployAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TraineeTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='upload date')),
                ('state', models.CharField(default='in_progress', max_length=100)),
                ('time_spent', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_training', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Easy', max_length=20)),
                ('estimatedDuration', models.IntegerField(default=0)),
                ('state_training', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('attempts_allowed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BlockAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_block', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], default='In progress', max_length=20)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.block')),
            ],
        ),
    ]
