# Generated by Django 5.0.1 on 2024-03-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0002_training_attempts_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='deploy_type',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='training',
        ),
        migrations.AlterField(
            model_name='training',
            name='state_training',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='BlockDeploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('estimed_duration_block', models.IntegerField(default=0)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training')),
            ],
        ),
        migrations.AddField(
            model_name='deploy',
            name='block_deploy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.blockdeploy'),
        ),
        migrations.DeleteModel(
            name='DeployType',
        ),
    ]
