# Generated by Django 5.0.4 on 2025-10-31 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainingApp', '0002_initial'),
        ('userApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.trainee'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.block'),
        ),
        migrations.AddField(
            model_name='choice',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploy'),
        ),
        migrations.AddField(
            model_name='deployanswer',
            name='block_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.blockanswer'),
        ),
        migrations.AddField(
            model_name='deployanswer',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploy'),
        ),
        migrations.AddField(
            model_name='deployanswer',
            name='selectedChoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.choice'),
        ),
        migrations.AddField(
            model_name='traineetraining',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.trainee'),
        ),
        migrations.AddField(
            model_name='blockanswer',
            name='trainee_Training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.traineetraining'),
        ),
        migrations.AddField(
            model_name='training',
            name='groups',
            field=models.ManyToManyField(to='trainingApp.group'),
        ),
        migrations.AddField(
            model_name='traineetraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AddField(
            model_name='comment',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AddField(
            model_name='block',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
    ]
