# Generated by Django 4.2.5 on 2023-09-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0003_deploy_deploy_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='count',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='deploy_question',
        ),
        migrations.AddField(
            model_name='training',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_question', models.CharField(max_length=500)),
                ('choice_text', models.CharField(max_length=200)),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploy')),
            ],
        ),
    ]
