# Generated by Django 4.2.5 on 2023-09-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0004_remove_deploy_choice_text_remove_deploy_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='deploy_question',
            new_name='question_text',
        ),
    ]
