# Generated by Django 5.0.1 on 2024-03-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0004_blockdeploy_state_block_deploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockdeploy',
            name='state_block_deploy',
        ),
    ]
