# Generated by Django 4.2.5 on 2023-09-27 18:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0005_rename_deploy_question_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='deploy_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='deploy_sound',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/sound'), upload_to=''),
        ),
    ]
