# Generated by Django 5.0.1 on 2024-03-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0005_remove_blockdeploy_state_block_deploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='block_deploy',
        ),
        migrations.RemoveField(
            model_name='deployanswer',
            name='trainee_Training',
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('estimed_duration_block', models.IntegerField(default=0)),
                ('state_block', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training')),
            ],
        ),
        migrations.AddField(
            model_name='deploy',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.block'),
        ),
        migrations.CreateModel(
            name='BlockAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_block', models.CharField(choices=[('In progress', 'In Progress'), ('Complated', 'Complated')], default='In progress', max_length=20)),
                ('block_deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.block')),
                ('trainee_Training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.traineetraining')),
            ],
        ),
        migrations.AddField(
            model_name='deployanswer',
            name='block_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.blockanswer'),
        ),
        migrations.DeleteModel(
            name='BlockDeploy',
        ),
    ]
