# Generated by Django 4.2.5 on 2023-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0007_remove_question_question_text_deploy_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
    ]
