# Generated by Django 5.0.1 on 2024-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0010_rename_gruops_training_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='state_block',
            field=models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='blockanswer',
            name='state_block',
            field=models.CharField(choices=[('En progreso', 'In Progress'), ('Completo', 'Complated')], default='En progreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='correct_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='question',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='difficulty',
            field=models.CharField(choices=[('Inicial', 'Easy'), ('Intermedio', 'Intemediate'), ('Avanzado', 'Advanced')], default='Inicial', max_length=20),
        ),
        migrations.AlterField(
            model_name='training',
            name='state_training',
            field=models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=20),
        ),
    ]
