# Generated by Django 4.2.5 on 2023-10-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0012_remove_training_count_deploy_choices_deploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='question_text',
        ),
    ]
