# Generated by Django 4.2.5 on 2023-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0013_remove_deploy_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='choices_deploy',
        ),
        migrations.AddField(
            model_name='deploy',
            name='ch_d1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deploy',
            name='ch_d2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deploy',
            name='ch_d3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deploy',
            name='ch_d4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deploy',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
