# Generated by Django 5.0.4 on 2024-08-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0014_training_name_training_en_training_name_training_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='correct_answer_en',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='correct_answer_es',
        ),
        migrations.RemoveField(
            model_name='deployanswer',
            name='user_response',
        ),
        migrations.AddField(
            model_name='choice',
            name='correctChoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployanswer',
            name='selectedChoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.choice'),
            preserve_default=False,
        ),
    ]
