# Generated by Django 4.2.5 on 2023-10-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0014_remove_deploy_choices_deploy_deploy_ch_d1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='user_response',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
