# Generated by Django 4.2.5 on 2023-10-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0015_deploy_user_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='question',
        ),
    ]
