# Generated by Django 4.2.8 on 2023-12-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainingApp', '0015_deploy_user_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='Type',
            field=models.CharField(choices=[('Basico', 'Basic'), ('Intermedio', 'Intemediate'), ('Avanzado', 'Advanced')], default='Basico', max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='estimatedDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='modificationDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='question',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('educationalLevel', models.CharField(choices=[('Primaria', 'Primary School'), ('Secundaria', 'High School'), ('Universidad', 'Collage'), ('Postgrado', 'Graduate')], default='Secundaria', max_length=20)),
                ('occupation', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
