# Generated by Django 4.2.8 on 2023-12-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0016_training_type_training_estimatedduration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainee',
        ),
    ]
