# Generated by Django 5.0.1 on 2024-01-16 19:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0017_rename_ch_d1_deploy_correct_answer_and_more'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='ans',
            name='trainee_block',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='estimateDuration',
            new_name='estimatedDuration',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='training_name',
            new_name='name_training',
        ),
        migrations.RemoveField(
            model_name='ans',
            name='question',
        ),
        migrations.AddField(
            model_name='ans',
            name='deploy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploy'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AddField(
            model_name='training',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='upload date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='state_training',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('in_Progress', 'In Progress')], default='in_Progress', max_length=20),
        ),
        migrations.AddField(
            model_name='deploy',
            name='deploy_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploytype'),
        ),
        migrations.CreateModel(
            name='TraineeTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='upload date')),
                ('state', models.CharField(default='in_Progress', max_length=100)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.trainee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training')),
            ],
        ),
        migrations.AddField(
            model_name='ans',
            name='trainee_Training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.traineetraining'),
        ),
        migrations.DeleteModel(
            name='TraineeBlock',
        ),
    ]
