# Generated by Django 4.2.8 on 2023-12-29 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0020_deploytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='ch_d1',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='ch_d2',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='ch_d3',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='ch_d4',
        ),
        migrations.AddField(
            model_name='deploy',
            name='deploy_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploytype'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, null=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.deploy')),
            ],
        ),
    ]
