# Generated by Django 4.2.8 on 2023-12-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0021_remove_deploy_ch_d1_remove_deploy_ch_d2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='training',
            new_name='deploy',
        ),
    ]
