# Generated by Django 4.2.8 on 2023-12-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0022_rename_training_choice_deploy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploy',
            old_name='user_response',
            new_name='correct_answer',
        ),
    ]
