# Generated by Django 4.2.8 on 2023-12-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0024_remove_training_type_training_diffculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='diffculty',
            new_name='difficulty',
        ),
    ]
