# Generated by Django 4.2.8 on 2024-01-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0025_rename_diffculty_training_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='upload date'),
        ),
    ]
