# Generated by Django 4.2.8 on 2024-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0027_training_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='state',
        ),
        migrations.AddField(
            model_name='traineetraining',
            name='state',
            field=models.CharField(default='in_progress', max_length=100),
        ),
    ]
