# Generated by Django 4.2.8 on 2024-01-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0028_remove_training_state_traineetraining_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineetraining',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
