# Generated by Django 4.2.8 on 2024-01-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0029_traineetraining_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='state_training',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('in_progress', 'In Progress')], default='in_progress', max_length=20),
        ),
    ]
