# Generated by Django 4.2.8 on 2024-01-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
        ('trainingApp', '0030_training_state_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_liked', models.CharField(choices=[('Well explained', 'Well Explained'), ('Interesting', 'Interesting'), ('Easy to understand', 'Easy To Understand')], max_length=20)),
                ('least_liked', models.CharField(choices=[('Too difficult', 'Too Difficult'), ('Not interesting', 'Not Interesting'), ('Poorly explained', 'Poorly Explained'), ('Confusing', 'Confusing'), ('Repetitive', 'Repetitive')], max_length=20)),
                ('comment_aditional', models.CharField(max_length=500)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('pub_date', models.DateTimeField(verbose_name='upload date')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.trainee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training')),
            ],
        ),
    ]
